parameters:

    foreman.processor:

        ###################################################################
        # You can tweak the values below.                                 #
        # See: https://github.com/naroga/foreman for a complete reference #
        ###################################################################

        interval: 0.5
        workers: 5
        timeout: 30

        ###################################################################
        # Do not change the configuration below this point.               #
        # These are references to the values at app/config/parameters.yml #
        # If you need to change these, change @app/config/parameters.yml  #
        ###################################################################

        host: %foreman.processor.host%
        port: %foreman.processor.port%

services:

    foreman.processor:
        class: AppBundle\Processor\Processor
        arguments: [%foreman.processor%, @kernel]

    foreman.accessor:
        class: AppBundle\Accessor\Accessor
        arguments:
            - "%foreman.processor.protocol%://%foreman.processor.host%:%foreman.processor.port%"
            - @jms_serializer