parameters:

    foreman.processor:
        interval: 0.5
        port: %foreman.processor.port%

services:
    foreman.processor:
        class: AppBundle\Processor\Processor
        arguments: [%foreman.processor%]